### ISSUE TITLE
Intel UHD Graphics 620 won't start (Ventura)

### ISSUE THREAD

**Issue by ultranorma** [psabadac/Acer-A515-51G-Hackintosh-OpenCore#2]
Intel UHD Graphics 620 won't start :(
What needs to be fixed in config.plist?

**Comment by psabadac** [comment]
Probably nothing, it works perfectly on my machine.

**Comment by ultranorma** [comment]
BIOS version of your machine?

**Comment by psabadac** [comment]
![image](https://user-images.githubusercontent.com/40405196/226711425-418f3566-719e-4ab3-b2a0-2123e16d93b6.png)

**Comment by psabadac** [comment]
Try the windows installer method - this one worked for me.
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#downloading-macos
